# Generated by Django 5.1 on 2024-09-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options'),
        ('members', '0002_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='user',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attendee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
            preserve_default=False,
        ),
    ]
