# Generated by Django 5.1 on 2024-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_rsvp_user_rsvp_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
